version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pm_postgres
    environment:
      POSTGRES_USER: pm
      POSTGRES_PASSWORD: pm
      POSTGRES_DB: pm
    ports:
      - "5433:5432"
    volumes:
      - pm_postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: pm_mongo
    ports:
      - "27018:27017"
    volumes:
      - pm_mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: pm_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - pm_neo4j_data:/data

volumes:
  pm_postgres_data:
  pm_mongo_data:
  pm_neo4j_data:
